language: node_js
node_js:
  - v7
  - v6
  - v5
  - v4
cache:
  directories:
    - node_modules
install:
  - npm install i2c-bus --ignore-scripts
  - npm install
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm prune
after_success:
  - npm run report-coverage
  - npm run build
  - npm run semantic-release
