language: node_js
node_js:
  - v7
  - v6
  - v5
  - v4
install:
  - npm install i2c-bus --ignore-scripts
  - npm install
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
